name: flame_gamepad
description: A flame plugin to allow for easy access to gamepad in your games (also keyboard when on emulator).
version: 0.1.0
author: Fireslime <contact@fireslime.xyz>
homepage: https://github.com/fireslime/flame_gamepad

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: xyz.fireslime.flamegamepad
    pluginClass: FlameGamepadPlugin
